---
- name: Retrieve all kubelet-serving certificates
  kubernetes.core.k8s_info:
    api_version: certificates.k8s.io/v1
    kind: CertificateSigningRequest
    kubeconfig: "{{ cluster_files.kubeconfig }}"
    field_selectors:
      - spec.signerName=kubernetes.io/kubelet-serving
    wait: true
  register: cluster_certificate_requests

- name: Approve pending certificates
  ansible.builtin.command:
    argv:
      - kubectl
      - certificate
      - approve
      - "{{ request.metadata.name }}"
      - "--kubeconfig={{ cluster_files.kubeconfig | ansible.builtin.expanduser }}"
  register: cluster_certs_approve_output
  changed_when: cluster_certs_approve_output.rc == 0
  loop: "{{ cluster_certificate_requests.resources }}"
  loop_control:
    label: "certificatesigningrequest/{{ request.metadata.name }}"
    loop_var: request
  when:
    - request.status.conditions is not defined

- name: Wait for approvals to clear
  kubernetes.core.k8s_info:
    api_version: certificates.k8s.io/v1
    kind: CertificateSigningRequest
    kubeconfig: "{{ cluster_files.kubeconfig }}"
    name: "{{ request.metadata.name }}"
    wait: true
    wait_condition:
      type: Approved
      status: "True"
  loop: "{{ cluster_certificate_requests.resources }}"
  loop_control:
    label: "certificatesigningrequest/{{ request.metadata.name }}"
    loop_var: request
  when:
    - request.status.conditions is not defined
