---
- name: Import variable setting tasks
  ansible.builtin.import_tasks:
    file: set_cluster_platform.yaml

- name: Import variable setting tasks
  ansible.builtin.import_tasks:
    file: set_cluster_provider.yaml

- name: Import server validation tasks
  ansible.builtin.import_tasks:
    file: validate_server_version.yaml
