---
- name: Retrieve cluster information
  kubernetes.core.k8s_cluster_info:
    kubeconfig: "{{ cluster_files.kubeconfig }}"
  register: cluster_information

- name: Determine if OpenShift or Kubernetes based on presence of OpenShift APIs
  ansible.builtin.set_fact:
    cluster_platform: |-
      {{
        (
          (
            cluster_information.apis.keys() |
            ansible.builtin.intersect(openshift_apis) |
            ansible.builtin.length
          ) ==
          (
            openshift_apis |
            ansible.builtin.length
          )
        ) |
        ansible.builtin.ternary("openshift", "kubernetes")
      }}
  vars:
    openshift_apis:
      - route.openshift.io/v1
      - project.openshift.io/v1
      - config.openshift.io/v1
