---
- name: Retrieve all nodes
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    kubeconfig: "{{ cluster_files.kubeconfig }}"
  register: cluster_nodes

- name: Extract provider information
  ansible.builtin.set_fact:
    cluster_provider: |-
      {{
        cluster_nodes.resources |
        ansible.builtin.selectattr("spec.providerID", "defined") |
        map(attribute="spec.providerID") |
        map("ansible.builtin.split", ":") |
        map("ansible.builtin.first") |
        ansible.builtin.unique |
        ansible.builtin.first
      }}
