---
- name: Retrieve cluster information
  kubernetes.core.k8s_cluster_info:
    kubeconfig: "{{ cluster_files.kubeconfig }}"
  register: cluster_information

- name: Fail playbook due to `wrong kubernetes version` error
  ansible.builtin.fail:
    msg: "`kubernetes` version: {{ version }}. please update `kubernetes` to version {{ cluster_minimum_versions.kubernetes }} or higher."
  vars:
    version: |-
      {{
        cluster_information.version.server.kubernetes.gitVersion |
        ansible.builtin.split("v") |
        ansible.builtin.last
      }}
  when:
    - version is ansible.builtin.version(cluster_minimum_versions.kubernetes, "<")

- name: Validate OpenShift server version
  when:
    - cluster_platform == "openshift"
  block:
    - name: Import executables role
      ansible.builtin.import_role:
        name: executables
        tasks_from: validate_oc

    - name: Retrieve OpenShift server version
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: ClusterVersion
        kubeconfig: "{{ cluster_files.kubeconfig }}"
        name: version
      register: cluster_cluster_version

    - name: Validate that version information was retrieved
      ansible.builtin.assert:
        that:
          - cluster_cluster_version.api_found
          - cluster_cluster_version.resources | ansible.builtin.length == 1
        fail_msg: Unable to retrieve OpenShift version information from cluster.
        success_msg: OpenShift version information retrieved.

    - name: Fail playbook due to `wrong openshift version` error
      ansible.builtin.fail:
        msg: "`openshift` version: {{ version }}. please update `openshift` to version {{ cluster_minimum_versions.openshift }} or higher."
      vars:
        version: "{{ cluster_cluster_version.resources[0].status.desired.version }}"
      when:
        - version is ansible.builtin.version(cluster_minimum_versions.openshift, "<")
