---
- name: Create Namespace for Clickhouse Operator managed instances
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          "itbench.io/gateway-access": shared
          "pod-security.kubernetes.io/audit": restricted
          "pod-security.kubernetes.io/audit-version": v1.35
          "pod-security.kubernetes.io/enforce": restricted
          "pod-security.kubernetes.io/enforce-version": v1.35
          "pod-security.kubernetes.io/warn": restricted
          "pod-security.kubernetes.io/warn-version": v1.35
          "prometheus.itbench.io/monitor": "true"
        name: "{{ tools_managers.clickhouse_operator.instances.kubernetes.namespace }}"
    state: present

# TODO: Add service account and give access to `nonroot-v2` for OpenShift

- name: Create Secret for Clickhouse installation default user
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: user-default-credentials
        namespace: "{{ tools_managers.clickhouse_operator.instances.kubernetes.namespace }}"
      type: Opaque
      stringData:
        user: default
        password: "" # pragma: allowlist secret
    state: present
  register: tools_clickhouse_default_user_secret

- name: Create ConfigMap for Prometheus database initialization
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        labels:
          "app.kubernetes.io/name": clickhouse
        name: clickhouse-init-prometheus
        namespace: "{{ tools_managers.clickhouse_operator.instances.kubernetes.namespace }}"
      data:
        01_init_prometheus.sql: |
          -- Based on https://clickhouse.com/docs/engines/table-engines/special/time_series
          -- Create database for Prometheus metrics
          CREATE DATABASE IF NOT EXISTS prometheus;

          -- Create the TimeSeries table with default schema
          CREATE TABLE IF NOT EXISTS prometheus.metrics
          ENGINE = TimeSeries;
    state: present
  register: tools_clickhouse_prometheus_config_map

- name: Create Clickhouse Installation
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: clickhouse.altinity.com/v1
      kind: ClickHouseInstallation
      metadata:
        labels:
          app.kubernetes.io/name: clickhouse
          app.kubernetes.io/version: 25.3.8.10041
        name: "{{ tools_managers.clickhouse_operator.instances.names.main }}"
        namespace: "{{ tools_managers.clickhouse_operator.instances.kubernetes.namespace }}"
      spec:
        configuration:
          settings:
            prometheus/asynchronous_metrics: "true"
            prometheus/endpoint: "/metrics"
            prometheus/errors: "true"
            prometheus/events: "true"
            prometheus/handlers/metrics_exporter/url: "/metrics"
            prometheus/handlers/metrics_exporter/handler/type: "expose_metrics"
            prometheus/handlers/remote_write_rule/handler/database: "prometheus"
            prometheus/handlers/remote_write_rule/handler/table: "metrics"
            prometheus/handlers/remote_write_rule/handler/type: "remote_write"
            prometheus/handlers/remote_write_rule/url: "/write"
            prometheus/metrics: "true"
            prometheus/port: 9363
          users:
            default/networks/ip: 0.0.0.0/0
            default/access_management: 1
            default/named_collection_control: 1
            default/show_named_collections: 1
            default/show_named_collections_secrets: 1
            default/password:
              valueFrom:
                secretKeyRef:
                  name: "{{ tools_clickhouse_default_user_secret.result.metadata.name }}"
                  key: password
          profiles:
            default/allow_experimental_time_series_table: 1
            default/http_connection_timeout: 30
          clusters:
            - name: main
              layout:
                shardsCount: 1
                replicasCount: 1
        defaults:
          templates:
            dataVolumeClaimTemplate: data-volume-template
            podTemplate: pod-template
            serviceTemplate: service-template
        templates:
          podTemplates:
            - name: pod-template
              metadata:
                labels:
                  app.kubernetes.io/name: clickhouse
                  app.kubernetes.io/version: 25.3.8.10041
              spec:
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: node-role.itbench.io/sandbox
                              operator: DoesNotExist
                securityContext:
                  fsGroup: 101
                  runAsGroup: 101
                  runAsNonRoot: true
                  runAsUser: 101
                  seccompProfile:
                    type: RuntimeDefault
                containers:
                  - name: clickhouse
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                    image: docker.io/altinity/clickhouse-server:25.3.8.10041.altinitystable
                    imagePullPolicy: IfNotPresent
                    ports:
                      - name: http
                        containerPort: 8123
                      - name: tcp
                        containerPort: 9000
                      - name: prometheus
                        containerPort: 9363
                    resources:
                      requests:
                        cpu: 100m
                        memory: 2Gi
                      limits:
                        memory: 6Gi
                    volumeMounts:
                      - name: initdb-volume
                        mountPath: /docker-entrypoint-initdb.d
                        readOnly: true
                volumes:
                  - name: initdb-volume
                    configMap:
                      name: "{{ tools_clickhouse_prometheus_config_map.result.metadata.name }}"
                      defaultMode: 0555
          serviceTemplates:
            - name: service-template
              metadata:
                labels:
                  app.kubernetes.io/name: clickhouse
                  app.kubernetes.io/version: 25.3.8.10041
              spec:
                type: ClusterIP
                ports:
                  - name: http
                    port: 8123
                    targetPort: 8123
                  - name: tcp
                    port: 9000
                    targetPort: 9000
                  - name: prometheus
                    port: 9363
                    targetPort: 9363
                selector:
                  app.kubernetes.io/name: clickhouse
          volumeClaimTemplates:
            - name: data-volume-template
              reclaimPolicy: Retain
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
    state: present

- name: Wait for Clickhouse installation to complete
  kubernetes.core.k8s_info:
    api_version: clickhouse.altinity.com/v1
    kind: ClickHouseInstallation
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    name: "{{ tools_managers.clickhouse_operator.instances.names.main }}"
    namespace: "{{ tools_managers.clickhouse_operator.instances.kubernetes.namespace }}"
  register: tools_chi
  until:
    - tools_chi.resources[0].status is defined
    - tools_chi.resources[0].status.status is defined
    - tools_chi.resources[0].status.status == 'Completed'
  retries: 10
  delay: 30

- name: Create ServiceMonitor for Clickhouse Installation
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: "{{ tools_managers.clickhouse_operator.instances.names.main }}"
        namespace: "{{ tools_managers.clickhouse_operator.instances.kubernetes.namespace }}"
      spec:
        selector:
          matchLabels:
            "app.kubernetes.io/name": clickhouse
        endpoints:
          - interval: 30s
            port: prometheus
    state: present
