---
- name: Import tasks to approve pending certificate requests
  ansible.builtin.include_role:
    name: cluster
    tasks_from: approve_certificate_requests
  vars:
    cluster_files:
      kubeconfig: "{{ tools_cluster.kubeconfig }}"
  when:
    - tools_cluster.provider == 'kind'

- name: Install SRE and FinOps Tools
  when:
    - ((tools_configuration.finops.enabled | ansible.builtin.default(false)) or (tools_configuration.sre.enabled | ansible.builtin.default(false)))
  block:
    - name: Import Prometheus installation tasks
      ansible.builtin.import_tasks:
        file: install_prometheus.yaml

    - name: Import Prometheus endpoint variable setting tasks
      ansible.builtin.import_tasks:
        file: set_internal_endpoints_prometheus.yaml

    - name: Import Clickhouse installation tasks
      ansible.builtin.import_tasks:
        file: install_clickhouse.yaml

    - name: Import Clickhouse credential variable setting tasks
      ansible.builtin.import_tasks:
        file: set_credentials_clickhouse.yaml

    - name: Import Clickhouse endpoint variable setting tasks
      ansible.builtin.import_tasks:
        file: set_internal_endpoints_clickhouse.yaml

    - name: Import Prometheus remote write configuration update tasks
      ansible.builtin.import_tasks:
        file: configure_prometheus_remote_write.yaml

    - name: Import OpenSearch installation tasks
      ansible.builtin.import_tasks:
        file: install_opensearch.yaml

    - name: Import OpenTelemetry installation tasks
      ansible.builtin.import_tasks:
        file: install_opentelemetry.yaml

    - name: Import Kubernetes Metrics Server installation tasks
      ansible.builtin.import_tasks:
        file: install_kubernetes_metrics_server.yaml

    - name: Install FinOps specific tools
      when:
        - tools_configuration.finops.enabled | ansible.builtin.default(false)
      block:
        - name: Import OpenCost installation tasks
          ansible.builtin.import_tasks:
            file: install_opencost.yaml

    - name: Install SRE specific tools
      when:
        - tools_configuration.sre.enabled | ansible.builtin.default(false)
      block:
        - name: Import Chaos Mesh installation tasks
          ansible.builtin.import_tasks:
            file: install_chaos_mesh.yaml

        - name: Import Kubernetes Topology Monitor installation tasks
          ansible.builtin.import_tasks:
            file: install_kubernetes_topology_monitor.yaml

    - name: Import Istio installation tasks
      ansible.builtin.import_tasks:
        file: install_istio.yaml

    - name: Import Kubernetes Gateway API installation tasks
      ansible.builtin.import_tasks:
        file: install_kubernetes_gateway.yaml
      when:
        - tools_cluster.platform == "kubernetes"

    - name: Import OpenShift Route installation tasks
      ansible.builtin.import_tasks:
        file: install_openshift_routes.yaml
      vars:
        route_response_headers:
          - name: Content-Security-Policy
            action:
              type: Set
              set:
                value: "img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; form-action 'none'; frame-ancestors 'none'"
          - name: Cross-Origin-Resource-Policy
            action:
              type: Set
              set:
                value: same-origin
          - name: Referrer-Policy
            action:
              type: Set
              set:
                value: strict-origin-when-cross-origin
          - name: X-Content-Type-Options
            action:
              type: Set
              set:
                value: nosniff
          - name: X-Frame-Options
            action:
              type: Set
              set:
                value: DENY
          - name: X-XSS-Protection
            action:
              type: Set
              set:
                value: "0"
      when:
        - tools_cluster.platform == "openshift"
