---
- name: Uninstall Prometheus Operator and Prometheus on Kubernetes
  when:
    - tools_cluster.platform == "kubernetes"
  block:
    - name: Uninstall Prometheus Operator and Prometheus
      kubernetes.core.helm:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        release_name: "{{ tools_managers.prometheus.helm.release.name }}"
        release_namespace: "{{ tools_managers.prometheus.kubernetes.namespace }}"
        release_state: absent
        wait: true
        timeout: "600s"

    - name: Delete Namespace for Prometheus
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        resource_definition:
          api_version: v1
          kind: Namespace
          metadata:
            name: "{{ tools_managers.prometheus.kubernetes.namespace }}"
        state: absent
        wait: true
        wait_timeout: 600

- name: Disable OpenShift User Workload Monitoring
  when:
    - tools_cluster.platform == "openshift"
  block:
    - name: Delete User Workload ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: user-workload-monitoring-config
            namespace: "{{ tools_managers.prometheus.openshift.namespace }}"
        state: absent

    - name: Delete Cluster Monitoring ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: cluster-monitoring-config
            namespace: openshift-monitoring
        state: absent
