---
- name: Import helm validation tasks
  ansible.builtin.import_tasks:
    file: validate_helm.yaml

- name: Import kubectl validation tasks
  ansible.builtin.import_tasks:
    file: validate_kubectl.yaml

- name: Import Python validation tasks
  ansible.builtin.import_tasks:
    file: validate_python.yaml
