---
- name: Import binary path validation tasks
  ansible.builtin.import_tasks:
    file: check_binary_path.yaml
  vars:
    binary_name: oc

- name: Check oc executable version
  ansible.builtin.command:
    argv:
      - "{{ executables_oc_path }}"
      - version
      - --client=true
      - -o
      - json
  register: executables_oc_raw_version
  changed_when:
    - false

- name: Parse oc executable version string
  ansible.builtin.set_fact:
    executables_oc_version: |-
      {{
        versions.clientVersion.gitVersion |
        ansible.builtin.split("v") |
        ansible.builtin.last
      }}
  vars:
    versions: |-
      {{
        executables_oc_raw_version.stdout |
        ansible.builtin.from_json
      }}

- name: Fail playbook due to `wrong binary version` error
  ansible.builtin.fail:
    msg: "`oc` version: {{ executables_oc_version }}. please update `oc` to version {{ executables_minimum_versions.oc }} or higher."
  when:
    - executables_oc_version is ansible.builtin.version(executables_minimum_versions.oc, "<")

- name: Display oc executable information
  ansible.builtin.debug:
    var: info
  vars:
    info:
      path: "{{ executables_oc_path }}"
      version: "{{ executables_oc_version }}"
