---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      docker_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
      docker_registry:
        required: true
        type: dict
        options:
          email:
            required: true
            type: str
          password:
            required: true
            type: str
          server:
            required: true
            type: str
          username:
            required: true
            type: str
