---
apiVersion: itbench.io/v1
kind: GroundTruth
metadata:
  name: scenario-50
spec:
  alerts:
    - group_id: productpage-v1-pod-1
      id: HighRequestErrorRate
      metadata:
        description: Increased error rate for product page service due to erroring requests
    - id: NoRequestsOpened
      metadata:
        description: Ratings service receiving no TCP connections from reviews due to upstream productpage mTLS failure
  aliases:
    - - productpage-v1-pod-1
      - productpage-v1-service-1
  fault:
    - category: Change
      condition: Peer authentication is applied to productpage-v1 service which cannot communicate to the other services
      entity:
        group_id: productpage-v1-service-1
        kind: Service
        name: productpage-v1-service-1
      fault_mechanism: custom
  groups:
    - filter:
        - productpage-v1-*
      id: productpage-v1-pod-1
      kind: Pod
      namespace: book-info
    - filter:
        - productpage-v1-*
      id: productpage-v1-service-1
      kind: Service
      namespace: book-info
      root_cause: true
    - filter:
        - reviews-v*
      id: reviews-service-1
      kind: Service
      namespace: book-info
    - filter:
        - ratings-v*
      id: ratings-service-1
      kind: Service
      namespace: book-info
  propagations:
    - condition: Strict mTLS peer authentication policy applied to productpage-v1
      effect: HTTP requests to productpage are denied, leading to an increased error rate
      source: productpage-v1-service-1
      target: productpage-v1-pod-1
    - condition: Productpage service fails to process requests successfully
      effect: Reviews service stops receiving valid work from productpage
      source: productpage-v1-pod-1
      target: reviews-service-1
    - condition: Reviews service has no valid requests to process
      effect: Reviews stops opening TCP connections to ratings service
      source: reviews-service-1
      target: ratings-service-1
  recommendedActions: []
