---
- name: Create Docker registry secret
  kubernetes.core.k8s:
    kubeconfig: "{{ docker_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: regcred
        namespace: default
      data:
        .dockerconfigjson: |-
          {{
            { "auths": config.auths } |
            ansible.builtin.to_json |
            ansible.builtin.b64encode
          }}
    state: present
  vars:
    config:
      auths:
        "{{ docker_registry.server }}":
          auth: "{{ (docker_registry.username + ':' + docker_registry.password) | ansible.builtin.b64encode }}" # pragma: allowlist secret
          email: "{{ docker_registry.email }}"
          password: "{{ docker_registry.password }}" # pragma: allowlist secret
          username: "{{ docker_registry.username }}"
