---
- name: Patch existing service accounts with imagePullSecrets
  kubernetes.core.k8s:
    kubeconfig: "{{ docker_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: default
        namespace: "{{ service_account_namespace }}"
      imagePullSecrets:
        - name: regcred
    state: patched
  loop:
    - default
    - kube-system
  loop_control:
    label: namespace/{{ service_account_namespace }}
    loop_var: service_account_namespace
