---
- name: Import Docker registry secret creation tasks
  ansible.builtin.import_tasks:
    file: install_registry_secret.yaml

- name: Import Kyverno installation tasks
  ansible.builtin.import_tasks:
    file: install_kyverno.yaml

- name: Import ServiceAcount patching tasks
  ansible.builtin.import_tasks:
    file: install_image_pull_secrets.yaml
