---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      aws_cluster_group:
        required: true
        type: dict
        options:
          name:
            required: true
            type: dict
            options:
              prefix:
                required: true
                type: str
      aws_configuration:
        required: true
        type: dict
        options:
          region:
            required: true
            type: str
          vpc:
            required: false
            type: dict
            options:
              cidr:
                required: true
                type: str
              nat_gateway:
                required: false
                type: dict
                options:
                  elastic_ip_allocation_id:
                    required: true
                    type: str
              subnets:
                required: true
                type: dict
                options:
                  count:
                    required: true
                    type: int
          zones:
            elements: str
            required: true
            type: list
