---
- name: Set scenario variables
  ansible.builtin.set_fact:
    scenarios_scenario: |-
      {{
        lookup(
          'ansible.builtin.file',
          [directory_path, 'scenario.yaml'] | ansible.builtin.path_join
        ) |
        ansible.builtin.from_yaml
      }}
    scenarios_ground_truth: |-
      {{
        lookup(
          'ansible.builtin.file',
          [directory_path, 'groundtruth.yaml'] | ansible.builtin.path_join
        ) |
        ansible.builtin.from_yaml
      }}
  vars:
    directory_path: |-
      {{
        [
          role_path,
          "files",
          [
            'scenario',
            scenarios_identifier
          ] | ansible.builtin.join('_')
        ] |
        ansible.builtin.path_join
      }}
  tags:
    - always

- name: Set scenario tools configuration
  ansible.builtin.set_fact:
    scenarios_tools:
      clickhouse: "{{ scenarios_scenario.spec.tools.sre.enabled | default(false) or scenarios_scenario.spec.tools.finops.enabled | default(false) }}"
      jaeger: "{{ scenarios_scenario.spec.tools.sre.enabled | default(false) or scenarios_scenario.spec.tools.finops.enabled | default(false) }}"
      kubernetes_topology_monitor: "{{ scenarios_scenario.spec.tools.sre.enabled | default(false) }}"
      prometheus: "{{ scenarios_scenario.spec.tools.sre.enabled | default(false) or scenarios_scenario.spec.tools.finops.enabled | default(false) }}"
  tags:
    - always
