---
- name: Create export directory
  ansible.builtin.file:
    mode: "0755"
    path: "{{ export_directory }}"
    state: directory
  register: kops_export_directory

- name: Export kubeconfig
  ansible.builtin.command:
    argv:
      - kops
      - export
      - --name
      - "{{ cluster_name }}"
      - kubecfg
      - --admin
      - --state
      - "{{ kops_state_store }}"
      - --kubeconfig
      - "{{ [kops_export_directory.path, cluster_name] | ansible.builtin.path_join }}"
  loop: "{{ kops_cluster_group.clusters }}"
  loop_control:
    label: cluster/{{ cluster_name }}
    loop_var: cluster_name
  register: kops_export_result
  changed_when: kops_export_result.rc == 0

- name: Display the export environment variable commands for all clusters
  ansible.builtin.debug:
    msg:
      - "Run the following command to access the cluster ({{ cluster_path | basename }}) using kubectl:"
      - "export KUBECONFIG={{ cluster_path }}"
  loop: "{{ kops_export_paths }}"
  loop_control:
    label: "{{ cluster_path | basename }}"
    loop_var: cluster_path
  vars:
    kops_export_paths: |-
      {{
        [kops_export_directory.path] |
        product(kops_cluster_group.clusters) |
        map("ansible.builtin.path_join") |
        map("ansible.builtin.realpath")
      }}
