recorders_managers:
  data_recorders:
    kubernetes:
      namespace: data-recorders
    instances:
      clickhouse: clickhouse-recorder
      jaeger: jaeger-recorder
      kubernetes_topology_monitor: kubernetes-topology-monitor-recorder
      prometheus: prometheus-recorder
