apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: topology-monitor
  namespace: topology-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology-monitor
  template:
    metadata:
      annotations:
        openshift.io/required-scc: "restricted-v2"
      labels:
        app: topology-monitor
    spec:
      serviceAccountName: topology-monitor
      securityContext:
        fsGroup: 1000
      containers:
      - name: topology-monitor
        image: quay.io/it-bench/topology-monitor:0.0.4
        imagePullPolicy: Always
        command: ["python3.12"]
        args:
        - "main.py"
        - "--data-dir=/app/topology_data"
        - "--interval=300"
        - "--max-snapshots=10"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: topology-data
          mountPath: /app/topology_data
        resources:
          requests:
            memory: "256Mi"
            cpu: "1000m"
          limits:
            memory: "768Mi"
            cpu: "1500m"
  persistentVolumeClaimRetentionPolicy:
     whenDeleted: "Delete"
     whenScaled: "Delete"
  volumeClaimTemplates:
  - metadata:
      name: topology-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 200Mi
