---
apiVersion: itbench.io/v1
kind: GroundTruth
metadata:
  name: scenario-48
spec:
  alerts:
    - group_id: bookinfo-namespace-1
      id: NoRequestsOpened
      metadata:
        description: No requests detected for services in book-info due to ambient mode being disabled
    - group_id: bookinfo-namespace-1
      id: NoRequestsReceived
      metadata:
        description: Services show as unknown and receive no requests when ambient mode disabled
  aliases:
    - - bookinfo-namespace-1
  fault:
    - category: Change
      condition: Ambient mode is disabled in namespace
      entity:
        group_id: bookinfo-namespace-1
        kind: Namespace
        name: book-info
      fault_mechanism: misconfigured_service_mesh
  groups:
    - filter:
        - book-info
      id: bookinfo-namespace-1
      kind: Namespace
      namespace: book-info
      root_cause: true
  propagations:
    - condition: Ambient mode is disabled for book-info namespace
      effect: Pods in the book-info namespace will not be in the service mesh, leading to no traffic.
      source: bookinfo-namespace-1
      target: bookinfo-namespace-1
    - condition: Services not in mesh appear as unknown destinations
      effect: Service mesh observability shows no requests opened or received
      source: bookinfo-namespace-1
      target: bookinfo-namespace-1
  recommendedActions:
    - solution:
        actions:
          - Re-enable Istio ambient mode for the 'book-info' namespace by setting istio.io/dataplane-mode label.
          - Restart affected pods to ensure ambient mode is re-enabled.
        id: re_enable_ambient_mode
