---
- name: Manage AWS Resources
  hosts:
    - localhost
  pre_tasks:
    - name: Validate target variable
      ansible.builtin.assert:
        that:
          - target in ["awx-stack", "single-cluster"]
        fail_msg: Invalid target provided. Please provide valid target.
        success_msg: Valid target provided.
      tags:
        - always

    - name: Import system role
      ansible.builtin.import_role:
        name: system
  tasks:
    - name: Create role variables
      tags:
        - always
      block:
        - name: Create AWS configuration variable
          ansible.builtin.set_fact:
            aws_configuration:
              region: "{{ aws.region }}"
              vpc:
                cidr: "{{ aws.vpc.cidr }}"
                subnets:
                  count: "{{ 1 if target == 'single-cluster' else stack.runners.count + 1 }}"
              zones: "{{ aws.zones }}"

        - name: Add NAT gateway information to configuration
          ansible.builtin.set_fact:
            aws_configuration: |-
              {{
                aws_configuration |
                ansible.builtin.combine(
                  {
                    "vpc": {
                      "nat_gateway": aws.vpc.nat_gateway
                    }
                  },
                  recursive=true
                )
              }}
          when:
            - aws.vpc.nat_gateway is defined

        - name: Create AWS cluster group variable
          ansible.builtin.set_fact:
            aws_cluster_group:
              name:
                prefix: "{{ runner.name.prefix if target == 'single-cluster' else stack.name.prefix }}"

    - name: Import AWS role
      ansible.builtin.import_role:
        name: aws

    - name: Create AWS S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ aws.s3.bucket.name }}"
        region: "{{ aws.region }}"
        state: present
      tags:
        - create_clusters
