---
awx_managers:
  awx_operator:
    helm:
      chart:
        reference: awx-operator
        repository: https://ansible-community.github.io/awx-operator-helm
        version: 3.2.1
      release:
        name: awx-operator
    instances:
      names:
        main: awx-deployment
    kubernetes:
      namespace: awx
