---
docker_managers:
  kyverno:
    helm:
      chart:
        # renovate: datasource=docker depName=ghcr.io/kyverno/charts/kyverno
        reference: oci://ghcr.io/kyverno/charts/kyverno
        version: 3.6.3
      release:
        name: kyverno
    kubernetes:
      namespace: kyverno
