---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      waiters_cluster:
        options:
          kubeconfig:
            required: true
            type: str
        required: false
        type: dict
      waiters_tasks:
        elements: dict
        options:
          args:
            required: true
            type: dict
          id:
            choices:
              - delete-workload-pods
              - pause-execution
              - restart-kubernetes-workload
              - scale-kubernetes-workload
            required: true
            type: str
        required: true
        type: list
