---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      recorders_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
          platform:
            choices:
              - kubernetes
              - openshift
            required: true
            type: str
      recorders_configuration:
        required: false
        type: dict
        options:
          phase:
            choices:
              - pre-fault-injection
              - post-fault-injection
              - post-agent-execution
            required: true
            type: str
          tools:
            required: false
            type: dict
            options:
              finops:
                required: false
                type: dict
                options:
                  enabled:
                    default: false
                    required: false
                    type: bool
              sre:
                required: false
                type: dict
                options:
                  enabled:
                    default: false
                    required: false
                    type: bool
      recorders_storage:
        required: false
        type: dict
        options:
          local:
            required: false
            type: dict
            options:
              directory:
                required: true
                type: str
          s3:
            required: false
            type: dict
            options:
              bucket:
                required: true
                type: str
              directory:
                required: true
                type: str
              endpoint:
                required: true
                type: str
