---
- name: Create Kubernetes objects
  hosts:
    - environment
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: delete-workload-pods-test
        state: present

    - name: Create standard deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: test-deployment-standard
            namespace: delete-workload-pods-test
          spec:
            replicas: 2
            selector:
              matchLabels:
                app.kubernetes.io/name: test-deployment-standard
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: test-deployment-standard
              spec:
                containers:
                  - name: server
                    image: registry.access.redhat.com/ubi10-minimal:10.1-1773895769
                    command:
                      - /bin/sh
                    args:
                      - -c
                      - "sleep infinity"
        state: present
        wait: true

    - name: Create deployment with pending rollout
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: test-deployment-pending
            namespace: delete-workload-pods-test
          spec:
            replicas: 2
            selector:
              matchLabels:
                app.kubernetes.io/name: test-deployment-pending
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: test-deployment-pending
              spec:
                containers:
                  - name: server
                    image: registry.access.redhat.com/ubi10-minimal:10.1-1773895769
                    command:
                      - /bin/sh
                    args:
                      - -c
                      - "sleep infinity"
        state: present
        wait: true


    - name: Create standard statefulset
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: test-statefulset-standard
            namespace: delete-workload-pods-test
          spec:
            replicas: 2
            selector:
              matchLabels:
                app.kubernetes.io/name: test-statefulset-standard
            serviceName: test-statefulset-standard
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: test-statefulset-standard
              spec:
                containers:
                  - name: server
                    image: registry.access.redhat.com/ubi10-minimal:10.1-1773895769
                    command:
                      - /bin/sh
                    args:
                      - -c
                      - "sleep infinity"
        state: present
        wait: true

    - name: Create statefulset with pending rollout
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: test-statefulset-pending
            namespace: delete-workload-pods-test
          spec:
            replicas: 2
            selector:
              matchLabels:
                app.kubernetes.io/name: test-statefulset-pending
            serviceName: test-statefulset-pending
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: test-statefulset-pending
              spec:
                containers:
                  - name: server
                    image: registry.access.redhat.com/ubi10-minimal:10.1-1773895769
                    command:
                      - /bin/sh
                    args:
                      - -c
                      - "sleep infinity"
        state: present
        wait: true

    - name: Import faults role
      ansible.builtin.import_role:
        name: faults
      vars:
        faults_cluster:
          kubeconfig: "{{ cluster.kubeconfig }}"
        faults_injection_tasks:
          - id: nonexistent-kubernetes-workload-node
            args:
              kubernetesObject:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: test-deployment-pending
                  namespace: delete-workload-pods-test
          - id: nonexistent-kubernetes-workload-node
            args:
              kubernetesObject:
                apiVersion: apps/v1
                kind: StatefulSet
                metadata:
                  name: test-statefulset-pending
                  namespace: delete-workload-pods-test
