---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-59
spec:
  alerts:
    - labels: {}
      name: KubeContainerWaiting
  entities:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: recommendation
        namespace: otel-demo
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: recommendation-config
        namespace: otel-demo
  solutions:
    - - steps:
          - command: kubectl -n otel-demo rollout undo deployment/recommendation
            text: Revert the last change done to the manifest.
      - steps:
          - command: kubectl -n otel-demo edit configmap recommendation-config
            text: Manually edit the manifest and replace the script with a functioning one.
      - steps:
          - command: kubectl -n otel-demo edit deployment recommendation
            text: Manually edit the manifest and remove the faulty init container.
