---
apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-49
spec:
  applications:
    opentelemetryDemo:
      enabled: true
  faults:
    - injections:
        - args:
            container:
              name: frontend
            kubernetesObject:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: frontend
                namespace: otel-demo
          id: misconfigured-kubernetes-workload-container-readiness-probe
      waitFor:
        postInjection:
          - args:
              kubernetesObject:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: cart
                  namespace: otel-demo
            id: delete-workload-pods
  tools:
    sre:
      enabled: true
