---
- name: Destroy Kubernetes objects
  hosts:
    - environment
  tasks:
    - name: Delete namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: crashing-kubernetes-workload-init-container-test
        state: absent
        wait: true
