---
- name: Verify that fault injection succeeded
  hosts:
    - environment
  tasks:
    - name: Retrieve workload
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: apps/v1
        kind: Deployment
        name: compromised-workload
        namespace: crashing-kubernetes-workload-init-container-test
      register: faults_deployment

    - name: Validate that init container was added
      ansible.builtin.assert:
        that:
          - faults_deployment.resources[0].spec.template.spec.initContainers is defined
          - faults_deployment.resources[0].spec.template.spec.initContainers | length > 0
          - faults_deployment.resources[0].spec.template.spec.initContainers[0].name == "worker"
        fail_msg: Init container was not added to the workload. Fault injection failed.
        success_msg: Init container was successfully added to the workload.

    - name: Retrieve ConfigMap
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: v1
        kind: ConfigMap
        name: compromised-workload-config
        namespace: crashing-kubernetes-workload-init-container-test
      register: faults_configmap

    - name: Validate that ConfigMap was created
      ansible.builtin.assert:
        that:
          - faults_configmap.resources | length == 1
          - faults_configmap.resources[0].data.config is defined
          - faults_configmap.resources[0].data.script is defined
        fail_msg: ConfigMap was not created. Fault injection failed.
        success_msg: ConfigMap was successfully created.

    - name: Validate that volumes were added
      ansible.builtin.assert:
        that:
          - faults_deployment.resources[0].spec.template.spec.volumes is defined
          - faults_deployment.resources[0].spec.template.spec.volumes | length >= 2
        fail_msg: Volumes were not added to the workload. Fault injection failed.
        success_msg: Volumes were successfully added to the workload.
