---
- name: Extract CIDR address base
  ansible.builtin.set_fact:
    aws_vpc_cidr_base: |-
      {{
        [
          cidr_components[0],
          cidr_components[1]
        ] |
        ansible.builtin.join(".")
      }}
  vars:
    cidr_components: "{{ aws_configuration.vpc.cidr | ansible.builtin.split('.') }}"

- name: Create VPC
  amazon.aws.ec2_vpc_net:
    cidr_block: "{{ aws_configuration.vpc.cidr }}"
    name: "{{ aws_cluster_group.name.prefix }}-vpc"
    region: "{{ aws_configuration.region }}"
    state: present
    tags:
      ClusterGroup: "{{ aws_cluster_group.name.prefix }}"
      ManagedBy: ansible
      Name: "{{ aws_cluster_group.name.prefix }}-vpc"
  register: aws_vpc

- name: Create VPC Internet Gateway
  amazon.aws.ec2_vpc_igw:
    region: "{{ aws_configuration.region }}"
    state: present
    tags:
      ClusterGroup: "{{ aws_cluster_group.name.prefix }}"
      ManagedBy: ansible
      Name: "{{ aws_cluster_group.name.prefix }}-igw-gateway"
    vpc_id: "{{ aws_vpc.vpc.id }}"
  register: aws_igw

- name: Create VPC public subnet(s)
  amazon.aws.ec2_vpc_subnet:
    az: "{{ aws_configuration.zones | ansible.builtin.first }}"
    cidr: "{{ aws_vpc_cidr_base }}.{{ subnet_octet }}.0/24"
    map_public: true
    region: "{{ aws_configuration.region }}"
    state: present
    tags:
      ClusterGroup: "{{ aws_cluster_group.name.prefix }}"
      ManagedBy: ansible
      Name: "{{ aws_cluster_group.name.prefix }}-public-subnet-{{ subnet_octet | ansible.builtin.string }}"
    vpc_id: "{{ aws_vpc.vpc.id }}"
    wait: true
  loop: "{{ range(1, aws_configuration.vpc.subnets.count + 1) | ansible.builtin.list }}"
  loop_control:
    label: subnet/{{ subnet_octet }}
    loop_var: subnet_octet
  register: aws_vpc_subnets_public

- name: Verify that all subnets were created
  ansible.builtin.assert:
    that:
      - (aws_vpc_subnets_public.results | ansible.builtin.length) == aws_configuration.vpc.subnets.count
    fail_msg: All subnets were not created. Please retry.
    success_msg: All subnets were created.

- name: Create VPC route table for public subnets
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ aws_vpc.vpc.id }}"
    region: "{{ aws_configuration.region }}"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ aws_igw.gateway_id }}"
    tags:
      ClusterGroup: "{{ aws_cluster_group.name.prefix }}"
      ManagedBy: ansible
      Name: "{{ aws_cluster_group.name.prefix }}-public-route-table"
    state: present
  register: aws_public_route_table

- name: Associate public subnets in batches of 10
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ aws_vpc.vpc.id }}"
    region: "{{ aws_configuration.region }}"
    route_table_id: "{{ aws_public_route_table.route_table.id }}"
    lookup: id
    subnets: "{{ subnet_ids }}"
    purge_subnets: false
    purge_routes: false
  loop: |
    {{
      aws_vpc_subnets_public.results |
      map(attribute="subnet.id") |
      ansible.builtin.batch(10)
    }}
  loop_control:
    label: batch-{{ batch_index }}
    loop_var: subnet_ids
    index_var: batch_index
    pause: 2

- name: Configure NAT Gateway with private subnets
  when:
    - aws_configuration.vpc.nat_gateway is defined
  block:
    - name: Create VPC NAT Gateway
      amazon.aws.ec2_vpc_nat_gateway:
        allocation_id: "{{ aws_configuration.vpc.nat_gateway.elastic_ip_allocation_id }}"
        region: "{{ aws_configuration.region }}"
        state: present
        subnet_id: "{{ (aws_vpc_subnets_public.results | ansible.builtin.first).subnet.id }}"
        tags:
          ClusterGroup: "{{ aws_cluster_group.name.prefix }}"
          ManagedBy: ansible
          Name: "{{ aws_cluster_group.name.prefix }}-nat-gateway"
        wait: true
      register: aws_nat_gateway

    - name: Create VPC private subnet(s)
      amazon.aws.ec2_vpc_subnet:
        az: "{{ aws_configuration.zones | ansible.builtin.first }}"
        cidr: "{{ aws_vpc_cidr_base }}.{{ subnet_octet }}.0/24"
        map_public: false
        region: "{{ aws_configuration.region }}"
        state: present
        tags:
          ClusterGroup: "{{ aws_cluster_group.name.prefix }}"
          ManagedBy: ansible
          Name: "{{ aws_cluster_group.name.prefix }}-private-subnet-{{ subnet_octet | ansible.builtin.string }}"
        vpc_id: "{{ aws_vpc.vpc.id }}"
        wait: true
      loop: "{{ range(aws_configuration.vpc.subnets.count + 1, (aws_configuration.vpc.subnets.count * 2) + 1) | ansible.builtin.list }}"
      loop_control:
        label: subnet/{{ subnet_octet }}
        loop_var: subnet_octet
      register: aws_vpc_subnets_private

    - name: Verify that private to public subnet ratio is 1 to 1
      ansible.builtin.assert:
        that:
          - (aws_vpc_subnets_private.results | ansible.builtin.length) == (aws_vpc_subnets_public.results | ansible.builtin.length)
        fail_msg: All subnets were not created. Please retry.
        success_msg: All subnets were created.

    - name: Create VPC route table for private subnets
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ aws_vpc.vpc.id }}"
        region: "{{ aws_configuration.region }}"
        routes:
          - dest: "0.0.0.0/0"
            nat_gateway_id: "{{ aws_nat_gateway.nat_gateway_id }}"
        tags:
          ClusterGroup: "{{ aws_cluster_group.name.prefix }}"
          ManagedBy: ansible
          Name: "{{ aws_cluster_group.name.prefix }}-nat-private-route-table"
        state: present
      register: aws_private_nat_route_table

    - name: Associate private subnets with NAT route table in batches of 10
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ aws_vpc.vpc.id }}"
        region: "{{ aws_configuration.region }}"
        route_table_id: "{{ aws_private_nat_route_table.route_table.id }}"
        lookup: id
        subnets: "{{ subnet_ids }}"
        purge_subnets: false
        purge_routes: false
      loop: |
        {{
          aws_vpc_subnets_private.results |
          map(attribute="subnet.id") |
          ansible.builtin.batch(10)
        }}
      loop_control:
        label: batch-{{ batch_index }}
        loop_var: subnet_ids
        index_var: batch_index
        pause: 2
