---
- name: Import configuration validation tasks
  ansible.builtin.import_tasks:
    file: validate.yaml

- name: Import AWS networking resources creation tasks
  ansible.builtin.import_tasks:
    file: create.yaml
  tags:
    - create_clusters

- name: Import AWS networking resources deletion tasks
  ansible.builtin.import_tasks:
    file: delete.yaml
  tags:
    - delete_clusters
