---
- name: Creation and Deletion Configuration Validation
  tags:
    - create_clusters
    - delete_clusters
  block:
    - name: Retieve all regions
      amazon.aws.aws_region_info:
      register: aws_regions

    - name: Validate that region exists
      ansible.builtin.assert:
        that: aws_configuration.region in regions
        fail_msg: "AWS Region not found. Please select from region: {{ regions }}"
        success_msg: AWS region found.
      vars:
        regions: "{{ aws_regions.regions | map(attribute='region_name') }}"

- name: Creation Only Configuration Validtion
  tags:
    - create_clusters
  block:
    - name: Gather available zones in the region
      amazon.aws.aws_az_info:
        region: "{{ aws_configuration.region }}"
        filters:
          state: available
      register: aws_availability_zones

    - name: Validate that zones are available
      ansible.builtin.assert:
        that: aws_configuration.zones | ansible.builtin.difference(zones) | ansible.builtin.length == 0
        fail_msg: "At least one zone is not available. Please select from available zones: {{ zones }}"
        success_msg: All zones in region are available.
      vars:
        zones: "{{ aws_availability_zones.availability_zones | map(attribute='zone_name') }}"

    - name: Retrieve VPC service quotas via CLI
      ansible.builtin.command:
        argv:
          - aws
          - service-quotas
          - list-service-quotas
          - --output
          - json
          - --region
          - "{{ aws_configuration.region }}"
          - --service-code
          - vpc
      register: aws_vpc_service_quotas_output
      changed_when: false
      failed_when: aws_vpc_service_quotas_output.rc != 0

    - name: Parse CLI output
      ansible.builtin.set_fact:
        aws_vpc_service_quotas: "{{ (aws_vpc_service_quotas_output.stdout | ansible.builtin.from_json).Quotas }}"

    - name: Retrieve all VPCs in region
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_configuration.region }}"
      register: aws_ec2_vpc_nets

    - name: Validate that VPC creation is possible
      ansible.builtin.assert:
        that:
          - (aws_ec2_vpc_nets.vpcs | ansible.builtin.length) + 1 <= vpc_quota[0].Value
        fail_msg: Unable to allocate resources to create VPC. Please either raise the account quota or delete unneeded vpcs in region.
        success_msg: VPC resource allocation possible.
      vars:
        vpc_quota: |-
          {{
            aws_vpc_service_quotas |
            ansible.builtin.selectattr(
              "QuotaName",
              "==",
              "VPCs per Region"
            )
          }}

    - name: Retrieve all Internet Gateways in region
      amazon.aws.ec2_vpc_igw_info:
        region: "{{ aws_configuration.region }}"
      register: aws_ec2_vpc_igw_gateways

    - name: Validate that Internet Gateway creation is possible
      ansible.builtin.assert:
        that:
          - (aws_ec2_vpc_igw_gateways.internet_gateways | ansible.builtin.length) + 1 <= gateway_quota[0].Value
        fail_msg: Unable to allocate resources to create Intergent Gateway. Please either raise the account quota or delete unneeded gateways in region.
        success_msg: Internet Gateway resource allocation possible.
      vars:
        gateway_quota: |-
          {{
            aws_vpc_service_quotas |
            ansible.builtin.selectattr(
              "QuotaName",
              "==",
              "Internet gateways per Region"
            )
          }}

    - name: Validate VPC subnet creation is possible
      ansible.builtin.assert:
        that:
          - (aws_configuration.vpc.subnets.count * 2) <= subnet_quota[0].Value
        fail_msg: Requested number of subnets is over region's quota limit (subnet_quota.Value). Please lower the amount or change the quota.
        success_msg: VPC subnet resource allocation possible.
      vars:
        subnet_quota: |-
          {{
            aws_vpc_service_quotas |
            ansible.builtin.selectattr(
              "QuotaName",
              "==",
              "Subnets per VPC"
            )
          }}

    - name: Validate NAT Gateway Elastic IP configuration
      when:
        - aws_configuration.vpc.nat_gateway is defined
      block:
        - name: Validate Elastic IP allocation id
          amazon.aws.ec2_eip_info:
            filters:
              allocation-id: "{{ aws_configuration.vpc.nat_gateway.elastic_ip_allocation_id }}"
            region: "{{ aws_configuration.region }}"
          register: aws_ec2_eip

        - name: Verify Elastic IP exists
          ansible.builtin.assert:
            that:
              - aws_ec2_eip.addresses | ansible.builtin.length == 0
            fail_msg: Elastic IP not found. Please verify the allocation ID is correct and exists in the target region.
            success_msg: Elastic IP found.
