---
- name: Create temporary directory for records from {{ python_recorder.name }}
  ansible.builtin.tempfile:
    prefix: "{{ python_recorder.export.path }}"
    state: directory
  register: recorders_export_directory

- name: Retrieve PersistentVolumeClaim for {{ python_recorder.name }}
  kubernetes.core.k8s_info:
    api_version: v1
    kind: PersistentVolumeClaim
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    name: "{{ python_recorder.name }}-records"
    namespace: "{{ recorders_managers.data_recorders.kubernetes.namespace }}"
  register: recorders_persistent_volume_claims

- name: Copy files from volume
  when:
    - recorders_persistent_volume_claims.api_found
    - recorders_persistent_volume_claims.resources | ansible.builtin.length == 1
  block:
    - name: Create Deployment to export records from {{ python_recorder.name }}
      kubernetes.core.k8s:
        kubeconfig: "{{ recorders_cluster.kubeconfig }}"
        resource_definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            labels:
              "app.kubernetes.io/managed-by": ITBench
              "app.kubernetes.io/name": "{{ python_recorder.name }}-exporter"
              "app.kubernetes.io/part-of": "{{ python_recorder.name }}"
            name: "{{ python_recorder.name }}-exporter"
            namespace: "{{ recorders_managers.data_recorders.kubernetes.namespace }}"
          spec:
            selector:
              matchLabels:
                "app.kubernetes.io/managed-by": ITBench
                "app.kubernetes.io/name": "{{ python_recorder.name }}-exporter"
                "app.kubernetes.io/part-of": "{{ python_recorder.name }}"
            template:
              metadata:
                labels:
                  "app.kubernetes.io/managed-by": ITBench
                  "app.kubernetes.io/name": "{{ python_recorder.name }}-exporter"
                  "app.kubernetes.io/part-of": "{{ python_recorder.name }}"
              spec:
                containers:
                  - name: exporter
                    image: registry.access.redhat.com/ubi10:10.1-1776145136
                    command:
                      - /bin/sh
                    args:
                      - -c
                      - "sleep 600"
                    resources:
                      requests:
                        cpu: 10m
                        memory: 50Mi
                      limits:
                        memory: 100Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                    volumeMounts:
                      - name: records
                        mountPath: /opt/app-root/src/records
                securityContext:
                  fsGroup: 1001
                  runAsUser: 1001
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
                volumes:
                  - name: records
                    persistentVolumeClaim:
                      claimName: "{{ recorders_persistent_volume_claims.resources[0].metadata.name }}"
            replicas: 1
        state: present
        wait: true

    - name: Retrieve record exporter pod
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        kubeconfig: "{{ recorders_cluster.kubeconfig }}"
        namespace: "{{ recorders_managers.data_recorders.kubernetes.namespace }}"
        label_selectors:
          - app.kubernetes.io/managed-by = ITBench
          - app.kubernetes.io/name = {{ python_recorder.name }}-exporter
          - app.kubernetes.io/part-of = {{ python_recorder.name }}
      register: recorders_pods

    - name: Validate that exporter pod exists
      ansible.builtin.assert:
        that:
          - recorders_pods.api_found
          - recorders_pods.resources | ansible.builtin.length == 1
        fail_msg: Unable to find recorder exporter pod. Please ensure deployment exists.
        success_msg: Found recorder exporter pod.

    # NOTE: `kubectl` is used in place of the `kubernetes.core` collection because
    #       the `k8_cp` module has an internal error when using it.

    - name: Copy records from pod
      ansible.builtin.command:
        argv:
          - kubectl
          - cp
          - "{{ recorders_pods.resources[0].metadata.namespace }}/{{ recorders_pods.resources[0].metadata.name }}:/opt/app-root/src/records"
          - "{{ recorders_export_directory.path }}"
          - --kubeconfig={{ recorders_cluster.kubeconfig | ansible.builtin.expanduser }}
      register: recorders_copy_result
      changed_when: recorders_copy_result.rc == 0
      retries: 8
      delay: 15

    - name: Delete Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ recorders_cluster.kubeconfig }}"
        resource_definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ python_recorder.name }}-exporter"
            namespace: "{{ recorders_managers.data_recorders.kubernetes.namespace }}"
        state: absent
        wait: true

- name: Retrieve all files in temporary directory for {{ python_recorder.name }}
  ansible.builtin.find:
    path: "{{ recorders_export_directory.path }}"
  register: recorders_exported_files

- name: Copy exported data into local directory
  when:
    - recorders_storage.local is defined
  block:
    - name: Create local directory for exported data
      ansible.builtin.file:
        mode: "0755"
        path: |-
          {{
            [
              recorders_storage.local.directory,
              python_recorder.export.path
            ] |
            ansible.builtin.path_join
          }}
        state: directory
      register: recorders_local_directory

    - name: Copy exported data into local directory
      ansible.builtin.copy:
        dest: |-
          {{
            [
              recorders_local_directory.path,
              (record.path | ansible.builtin.basename)
            ] |
            ansible.builtin.path_join
          }}
        mode: "0644"
        src: "{{ record.path }}"
      loop: "{{ recorders_exported_files.files }}"
      loop_control:
        label: file/{{ record.path | ansible.builtin.basename }}
        loop_var: record

- name: Upload exported data to S3 bucket
  amazon.aws.s3_object:
    bucket: "{{ recorders_storage.s3.bucket }}"
    endpoint_url: "{{ recorders_storage.s3.endpoint }}"
    mode: put
    object: |-
      {{
        [
          recorders_storage.s3.directory,
          python_recorder.export.path,
          (record.path | ansible.builtin.basename)
        ] |
        ansible.builtin.path_join
      }}
    src: "{{ record.path }}"
  loop: "{{ recorders_exported_files.files }}"
  loop_control:
    label: file/{{ record.path | ansible.builtin.basename }}
    loop_var: record
  when:
    - recorders_storage.s3 is defined

- name: Delete temporary directory for records from {{ python_recorder.name }}
  ansible.builtin.file:
    path: "{{ recorders_export_directory.path }}"
    state: absent
