---
- name: Import variable setting tasks
  ansible.builtin.import_role:
    name: tools
    tasks_from: set_credentials_clickhouse
  vars:
    tools_cluster:
      kubeconfig: "{{ recorders_cluster.kubeconfig }}"

- name: Wait for any ongoing jobs to be removed
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    name: "{{ recorders_managers.data_recorders.instances.clickhouse }}"
    namespace: "{{ recorders_managers.data_recorders.kubernetes.namespace }}"
  register: recorders_job
  until:
    - recorders_job.resources | ansible.builtin.length == 0
  retries: 6
  delay: 30

- name: Import recorder deployment tasks
  ansible.builtin.import_tasks:
    file: deploy_python_recorder.yaml
  vars:
    python_recorder:
      job:
        environment_variables:
          - name: CLICKHOUSE_ENDPOINT
            value: "{{ tools_clickhouse_endpoint.http }}"
          - name: CLICKHOUSE_USERNAME
            value: "{{ tools_clickhouse_username }}"
          - name: CLICKHOUSE_PASSWORD
            value: "{{ tools_clickhouse_password }}"
      name: "{{ recorders_managers.data_recorders.instances.clickhouse }}"
      scripts:
        requirements_file_path: "files/scripts/clickhouse/requirements.txt"
        scripts_file_path: "files/scripts/clickhouse/gather.py"
      volume:
        size: 2Gi
