---
- name: Import storage validation tasks
  ansible.builtin.import_tasks:
    file: validate_storage.yaml

- name: Retrieve CronJobs
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: CronJob
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    namespace: "{{ recorders_managers.data_recorders.kubernetes.namespace }}"
  register: recorders_cronjobs

- name: Suspend all CronJobs
  kubernetes.core.k8s:
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ cronjob.apiVersion }}"
      kind: "{{ cronjob.kind }}"
      metadata:
        name: "{{ cronjob.metadata.name }}"
        namespace: "{{ cronjob.metadata.namespace }}"
      spec:
        suspend: true
    state: patched
  loop: "{{ recorders_cronjobs.resources }}"
  loop_control:
    label: cronjob/{{ cronjob.metadata.name }}
    loop_var: cronjob

- name: Retrieve Jobs
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    namespace: "{{ recorders_managers.data_recorders.kubernetes.namespace }}"
  register: recorders_jobs

- name: Wait for all jobs to finish running
  kubernetes.core.k8s_info:
    api_version: "{{ job.apiVersion }}"
    kind: "{{ job.kind }}"
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    name: "{{ job.metadata.name }}"
    namespace: "{{ job.metadata.namespace }}"
  loop: "{{ recorders_jobs.resources }}"
  loop_control:
    label: job/{{ job.metadata.name }}
    loop_var: job
  register: recorders_job
  until:
    - (
        recorders_job.resources | ansible.builtin.length == 0
      ) or
      (
        recorders_job.resources[0].status.conditions |
        ansible.builtin.default([]) |
        ansible.builtin.length > 0
      )
  retries: 12
  delay: 30

- name: Import recorder export tasks
  ansible.builtin.import_tasks:
    file: copy_python_recorder_files.yaml
  vars:
    python_recorder:
      export:
        path: observability_information_from_clickhouse
      name: "{{ recorders_managers.data_recorders.instances.clickhouse }}"

- name: Import recorder export tasks
  ansible.builtin.import_tasks:
    file: copy_python_recorder_files.yaml
  vars:
    python_recorder:
      export:
        path: trace_information
      name: "{{ recorders_managers.data_recorders.instances.jaeger }}"

- name: Import recorder export tasks
  ansible.builtin.import_tasks:
    file: copy_python_recorder_files.yaml
  vars:
    python_recorder:
      export:
        path: topology_information
      name: "{{ recorders_managers.data_recorders.instances.kubernetes_topology_monitor }}"

- name: Import recorder export tasks
  ansible.builtin.import_tasks:
    file: copy_python_recorder_files.yaml
  vars:
    python_recorder:
      export:
        path: alerts
      name: "{{ recorders_managers.data_recorders.instances.prometheus }}"

- name: Delete the namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ recorders_managers.data_recorders.kubernetes.namespace }}"
    state: absent
    wait: true
