---
- name: Check for kOps
  ansible.builtin.command:
    cmd: which kops
  register: system_kops_path
  changed_when: false

- name: Validate that kOps exists
  ansible.builtin.assert:
    that: system_kops_path.stdout_lines | ansible.builtin.length > 0
    fail_msg: kOps is not installed. Please install kops.
    success_msg: Using kOps at {{ system_kops_path.stdout_lines[0] }}

- name: Check kOps version
  ansible.builtin.command:
    cmd: "{{ system_kops_path.stdout_lines[0] }} version --short"
  register: system_kops_version
  changed_when: false

- name: Validate the kOps version
  ansible.builtin.assert:
    that: "'1.31' is version_compare(system_kops_version.stdout, '<=')"
    fail_msg: "kOps version for system {{ system_kops_version.stdout }} must be at least 1.31 or later."
    success_msg: "kOps version {{ system_kops_version.stdout }} (>= 1.31) is OK."
