---
- name: Import system binary checking tasks
  tags:
    - always
  block:
    - name: Import AWS CLI check tasks
      ansible.builtin.import_tasks:
        file: check_aws_version.yaml

    - name: Import KOps check tasks
      ansible.builtin.import_tasks:
        file: check_kops_version.yaml
