---
- name: Create ITBench organization
  awx.awx.organization:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    description: Organization for ITBench
    name: ITBench
    state: present

- name: Create kubeconfig credential type
  awx.awx.credential_type:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    description: Credentials type for Kubeconfig
    inputs:
      fields:
        - id: kubeconfig
          type: string
          label: kubeconfig
          secret: true
          multiline: true
      required:
        - kubeconfig
    injectors: "{{ lookup('ansible.builtin.file', 'files/awx/credential_types/kubeconfig_injectors.json') }}"
    kind: cloud
    name: Kubeconfig
    state: present

- name: Create kubeconfig credentials for each runner
  awx.awx.credential:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    credential_type: Kubeconfig
    description: Kubeconfig file for a Kubernetes cluster
    inputs:
      kubeconfig: "{{ lookup('ansible.builtin.file', kubeconfig) }}"
    name: Cluster-{{ kubeconfig_index + 1 }}-Kubeconfig
    organization: ITBench
  loop: "{{ awx_configuration.runners.kubeconfigs }}"
  loop_control:
    index_var: kubeconfig_index
    label: kubeconfig/{{ kubeconfig | ansible.builtin.basename }}
    loop_var: kubeconfig

- name: Create credentials for ITBench Repository
  awx.awx.credential:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    credential_type: Source Control
    description: SSH Credentials for ITBench GitHub repository
    inputs:
      ssh_key_data: "{{ lookup('ansible.builtin.file', awx_configuration.github.itbench.ssh.private_key_path) }}"
      ssh_key_unlock: "{{ awx_configuration.github.itbench.ssh.private_key_passphrase }}"
    name: GitHub-ITBench
    organization: ITBench
    state: present
  when:
    - awx_configuration.github.itbench.ssh is defined

- name: Create credentials for LLM Agent
  awx.awx.credential:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    credential_type: Source Control
    description: SSH Credentials for LLM agent repository
    inputs:
      ssh_key_data: "{{ lookup('ansible.builtin.file', awx_configuration.github.agent.ssh.private_key_path) }}"
      ssh_key_unlock: "{{ awx_configuration.github.agent.ssh.private_key_passphrase }}"
    name: GitHub-LLM-Agent
    organization: ITBench
    state: present
  when:
    - awx_configuration.github.agent.ssh is defined

- name: Create credentials for AWS Cloud Provider
  when:
    - awx_configuration.providers.aws.enabled | ansible.builtin.default(false)
  block:
    - name: Retrieve AWS access key id
      ansible.builtin.command:
        argv:
          - aws
          - configure
          - get
          - aws_access_key_id
      register: awx_aws_access_key_id_output
      changed_when: false

    - name: Retrieve AWS secret access ke
      ansible.builtin.command:
        argv:
          - aws
          - configure
          - get
          - aws_secret_access_key
      register: awx_secret_access_key_output
      changed_when: false

    - name: Create credentials for AWS
      awx.awx.credential:
        controller_host: "{{ awx_controller_host }}"
        controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
        controller_username: admin
        credential_type: Amazon Web Services
        description: Credentials for AWS
        inputs:
          username: "{{ awx_aws_access_key_id_output.stdout }}"
          password: "{{ awx_secret_access_key_output.stdout }}" # pragma: allowlist secret
        name: AWS
        organization: ITBench
        state: present

- name: Create project for ITBench Repository
  awx.awx.project:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    credential: "{{ 'GitHub-ITBench' if awx_configuration.github.itbench.ssh is defined else omit }}"
    description: ITBench GitHub repository
    name: GitHub-ITBench
    organization: ITBench
    scm_allow_override: true
    scm_branch: "{{ awx_configuration.github.itbench.branch }}"
    scm_clean: true
    scm_delete_on_update: true
    scm_track_submodules: true
    scm_type: git
    scm_url: "{{ awx_configuration.github.itbench.url }}"
    state: present

- name: Create project for LLM Agent Repository
  awx.awx.project:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    credential: "{{ 'GitHub-LLM-Agent' if awx_configuration.github.agent.ssh is defined else omit }}"
    description: LLM Agent GitHub repository
    name: GitHub-LLM-Agent
    organization: ITBench
    scm_allow_override: true
    scm_branch: "{{ awx_configuration.github.agent.branch }}"
    scm_clean: true
    scm_delete_on_update: true
    scm_track_submodules: false
    scm_type: git
    scm_url: "{{ awx_configuration.github.agent.url }}"
    state: present

- name: Create ITBench inventory
  awx.awx.inventory:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    description: Inventory for ITBench
    name: ITBench
    organization: ITBench
    state: present

- name: Create localhost host
  awx.awx.host:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    name: localhost
    inventory: ITBench
    variables:
      ansible_connection: local
    state: present

- name: Add localhost to environment and runner groups
  awx.awx.group:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    name: "{{ group_vars_name }}"
    inventory: ITBench
    hosts:
      - localhost
    state: present
  loop:
    - environment
    - runner
  loop_control:
    label: group_vars/{{ group_vars_name }}
    loop_var: group_vars_name

# ToDo: Revert back to this instead of static allocation once upstream AWX issue on syncing inventories is resolved
# - name: Create ITBench inventory source
#   awx.awx.inventory_source:
#     controller_host: "{{ awx_controller_host }}"
#     controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
#     controller_username: admin
#     inventory: ITBench
#     name: SRE
#     organization: ITBench
#     description: Inventory for ITBench
#     source: scm
#     source_path: sre/inventory.yaml
#     source_project: GitHub-ITBench

# - name: Sync ITBench inventory source to populate hosts
#   awx.awx.inventory_source_update:
#     controller_host: "{{ awx_controller_host }}"
#     controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
#     controller_username: admin
#     inventory_source: SRE
#     inventory: ITBench
#     wait: true
#     timeout: 300

- name: Add custom environment for running ITBench scenarios
  awx.awx.execution_environment:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    description: Custom environment for running ITBench scenarios
    image: quay.io/it-bench/awx-ee:2.0.0
    name: ITBench-Custom-EE
    organization: ITBench
    pull: always
