---
- name: Import project configuration tasks
  ansible.builtin.import_tasks:
    file: configure_projects.yaml

- name: Import job configuration tasks
  ansible.builtin.import_tasks:
    file: configure_jobs.yaml

- name: Import workflow configuration tasks
  ansible.builtin.import_tasks:
    file: configure_workflows.yaml
