---
- name: Include tasks to approve pending certificate requests
  ansible.builtin.include_role:
    name: cluster
    tasks_from: approve_certificate_requests
  vars:
    cluster_files:
      kubeconfig: "{{ awx_cluster.kubeconfig }}"
  when:
    - awx_cluster.provider == "kind"

- name: Import AWX operator installation tasks
  ansible.builtin.import_tasks:
    file: install_awx_operator.yaml

- name: Import AWX instance installation tasks
  ansible.builtin.import_tasks:
    file: install_awx_instances.yaml
