---
- name: Generate run identifier (UUID4)
  ansible.builtin.command:
    cmd: uuidgen
  changed_when: false
  register: awx_run_uuid

- name: Generate scenario and trial runner groupings
  ansible.builtin.set_fact:
    awx_scenario_trial_groups: |
      {{
        awx_experiments.scenarios |
        product(range(1, awx_experiments.trials + 1))
      }}

- name: Launch the scenario start execution workflow
  awx.awx.workflow_launch:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    extra_vars:
      storage: |-
        {{
          lookup("ansible.builtin.template", "templates/awx/workflows/vars/storage.j2") |
          ansible.builtin.from_yaml
        }}
    workflow_template: Scenario-{{ item[0] }}-Partial-Execution-Start
    wait: false
  loop: "{{ awx_scenario_trial_groups }}"
  loop_control:
    label: Scenario-{{ item[0] }}/Trial-{{ item[1] }}
  vars:
    run_directory: "{{ awx_agent.version }}/{{ awx_run_uuid.stdout }}/{{ item[0] }}/{{ item[1] }}"
  when:
    - awx_experiments.phase == "start"

- name: Launch the scenario stop execution workflow
  awx.awx.workflow_launch:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    extra_vars:
      storage: |-
        {{
          lookup("ansible.builtin.template", "templates/awx/workflows/vars/storage.j2") |
          ansible.builtin.from_yaml
        }}
    workflow_template: Scenario-{{ item[0] }}-Partial-Execution-Stop
    wait: false
  loop: "{{ awx_scenario_trial_groups }}"
  loop_control:
    label: Scenario-{{ item[0] }}/Trial-{{ item[1] }}
  vars:
    run_directory: "{{ awx_agent.version }}/{{ awx_run_uuid.stdout }}/{{ item[0] }}/{{ item[1] }}"
  when:
    - awx_experiments.phase == "stop"

- name: Launch the scenario full execution workflow
  awx.awx.workflow_launch:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    extra_vars:
      storage: |-
        {{
          lookup("ansible.builtin.template", "templates/awx/workflows/vars/storage.j2") |
          ansible.builtin.from_yaml
        }}
    workflow_template: Scenario-{{ item[0] }}-Full-Execution
    wait: false
  loop: "{{ awx_scenario_trial_groups }}"
  loop_control:
    label: Scenario-{{ item[0] }}/Trial-{{ item[1] }}
  vars:
    run_directory: "{{ awx_agent.version }}/{{ awx_run_uuid.stdout }}/{{ item[0] }}/{{ item[1] }}"
  when:
    - awx_experiments.phase == "full"

- name: Launch the scenario data collection execution workflow
  awx.awx.workflow_launch:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    extra_vars:
      storage: |-
        {{
          lookup("ansible.builtin.template", "templates/awx/workflows/vars/storage.j2") |
          ansible.builtin.from_yaml
        }}
    workflow_template: Scenario-{{ item[0] }}-Data-Collection-Execution
    wait: false
  loop: "{{ awx_scenario_trial_groups }}"
  loop_control:
    label: Scenario-{{ item[0] }}/Trial-{{ item[1] }}
  vars:
    run_directory: "{{ awx_agent.version }}/{{ awx_run_uuid.stdout }}/{{ item[0] }}/{{ item[1] }}"
  when:
    - awx_experiments.phase == "data_collection"
