---
- name: Get AWX secret information
  kubernetes.core.k8s_info:
    kind: Secret
    kubeconfig: "{{ awx_cluster.kubeconfig }}"
    name: "{{ awx_managers.awx_operator.instances.names.main }}-admin-password"
    namespace: "{{ awx_managers.awx_operator.kubernetes.namespace }}"
  register: awx_admin_secret

- name: Validate that secret exists
  ansible.builtin.assert:
    that:
      - awx_admin_secret.api_found
      - awx_admin_secret.resources | ansible.builtin.length == 1
    fail_msg: Unable to find admin secret. Please ensure AWX installed correctly.
    success_msg: Found admin secret.

- name: Extract the AWX password
  ansible.builtin.set_fact:
    awx_controller_password: "{{ awx_admin_secret.resources[0].data.password | ansible.builtin.b64decode }}" # pragma: allowlist secret
