---
- name: Import AWX instance uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_awx_instances.yaml

- name: Import AWX operator uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_awx_operator.yaml
