---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      cluster_files:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
