---
- name: Load faults library index
  ansible.builtin.set_fact:
    faults_library_index: |-
      {{
        lookup('ansible.builtin.file', index_file_path) |
        ansible.builtin.from_json
      }}
  vars:
    index_file_path: "{{ playbook_dir }}/../roles/documentation/files/library/faults/index.json"

- name: Generate faults library index-task map
  ansible.builtin.set_fact:
    faults_library_map: |-
      {{
        faults_library_map |
        ansible.builtin.default({}) |
        ansible.builtin.combine(
          {
            fault.id: {
              "taskFile": task_file
            }
          }
        )
      }}
  loop: "{{ faults_library_index }}"
  loop_control:
    label: fault/{{ fault.id }}
    loop_var: fault
  vars:
    task_file: inject_{{ fault.id | ansible.builtin.replace('-', '_') }}.yaml

- name: Create faults library index-task map file
  ansible.builtin.copy:
    content: |
      {{
        faults_library_map |
        ansible.builtin.to_nice_json
      }}
    dest: "{{ [role_path, 'files', 'library', 'map.json'] | ansible.builtin.path_join }}"
    mode: "0644"

- name: Create faults roles meta argument specs file
  ansible.builtin.copy:
    content: "{{ faults_argument_specs | ansible.builtin.to_nice_yaml(explicit_start=true, indent=2) }}"
    dest: "{{ [role_path, 'meta', 'argument_specs.yaml'] | ansible.builtin.path_join }}"
    mode: "0644"
  vars:
    faults_argument_specs: |-
      {{
        lookup('ansible.builtin.template', 'templates/meta/argument_specs.j2') |
        ansible.builtin.from_yaml
      }}

- name: Create fault injection tasks files
  ansible.builtin.copy:
    content: |
      ---
      - name: Print message
        ansible.builtin.debug:
          msg: This fault injection ({{ fault.id }}) is unimplemented.
    dest: "{{ [role_path, 'tasks', task_file_name] | ansible.builtin.path_join }}"
    force: false
    mode: "0644"
  loop: "{{ faults_library_index }}"
  loop_control:
    label: fault/{{ fault.id }}
    loop_var: fault
  vars:
    task_file_name: inject_{{ fault.id | ansible.builtin.replace('-', '_') }}.yaml
