---
- name: Retrieve workload
  kubernetes.core.k8s_info:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    api_version: "{{ injection_task.args.kubernetesObject.apiVersion }}"
    kind: "{{ injection_task.args.kubernetesObject.kind }}"
    name: "{{ injection_task.args.kubernetesObject.metadata.name }}"
    namespace: "{{ injection_task.args.kubernetesObject.metadata.namespace }}"
  register: faults_workload

- name: Validate that workload exists
  ansible.builtin.assert:
    that:
      - faults_workload.api_found
      - faults_workload.resources | ansible.builtin.length == 1
    fail_msg: Unable to find workload. Please verify that the workload exists.
    success_msg: Found workload.

- name: Update workload init containers
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_workload.resources[0].apiVersion }}"
      kind: "{{ faults_workload.resources[0].kind }}"
      metadata:
        name: "{{ faults_workload.resources[0].metadata.name }}"
        namespace: "{{ faults_workload.resources[0].metadata.namespace }}"
      spec:
        template:
          spec:
            initContainers:
              - name: worker
                image: registry.access.redhat.com/ubi10-minimal:10.1-1773895769
                command:
                  - /bin/sh
                args:
                  - -c
                  - "sleep infinity"
    state: patched
