---
apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-56
spec:
  applications:
    opentelemetryDemo:
      enabled: true
  faults:
    - injections:
        - args:
            container:
              name: product-catalog
            kubernetesObject:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: product-catalog
                namespace: otel-demo
          id: nonexistent-kubernetes-workload-container-image
      waitFor:
        postInjection:
          - args:
              kubernetesObject:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: checkout
                  namespace: otel-demo
            id: delete-workload-pods
  tools:
    sre:
      enabled: true
