---
- name: Manage SRE and FinOps AWX Stack
  hosts:
    - runner
  pre_tasks:
    - name: Import executables role
      ansible.builtin.import_role:
        name: executables
      tags:
        - always

    - name: Import cluster role
      ansible.builtin.import_role:
        name: cluster
      tags:
        - always
      vars:
        cluster_files:
          kubeconfig: "{{ stack.awx.kubeconfig }}"
  tasks:
    - name: Import role variables
      tags:
        - configure_pipeline
      block:
        - name: Create configuration variable
          ansible.builtin.set_fact:
            awx_configuration:
              agent:
                configuration: "{{ agent_configuration.configuration }}"
              github: "{{ github }}"
              runners:
                kubeconfigs: "{{ stack.runners.kubeconfigs }}"

        - name: Add providers variable
          ansible.builtin.set_fact:
            awx_configuration: "{{ awx_configuration | combine({'providers': {'aws': {'enabled': true}}}) }}"
          when:
            - cluster_provider != "kind"

    - name: Import role variables
      tags:
        - configure_pipeline
        - launch_workflows
      block:
        - name: Create experiments variable
          ansible.builtin.set_fact:
            awx_experiments:
              agent:
                version: "{{ agent_configuration.version }}"
              phase: "{{ run_phase | ansible.builtin.default('full') }}"
              scenarios: "{{ experiments.scenarios }}"
              storage: "{{ storage }}"
              trials: "{{ experiments.trials }}"

    - name: Import awx role
      ansible.builtin.import_role:
        name: awx
      vars:
        awx_cluster:
          kubeconfig: "{{ stack.awx.kubeconfig }}"
          provider: "{{ cluster_provider }}"
