---
- name: Manage SRE and FinOps Scenario Data Recorder Stack
  hosts:
    - environment
  pre_tasks:
    - name: Import executables role
      ansible.builtin.import_role:
        name: executables
      tags:
        - always

    - name: Import cluster role
      ansible.builtin.import_role:
        name: cluster
      tags:
        - always
      vars:
        cluster_files:
          kubeconfig: "{{ cluster.kubeconfig }}"
  tasks:
    - name: Import role variables from scenario
      tags:
        - install_recorders
      when:
        - scenario_id is defined
      block:
        - name: Import scenarios role
          ansible.builtin.import_role:
            name: scenarios
          vars:
            scenarios_identifier: "{{ scenario_id }}"

        - name: Create recorders installation variable
          ansible.builtin.set_fact:
            recorders_configuration:
              phase: "{{ benchmark_phase | ansible.builtin.default('pre-fault-injection') }}"
              tools: "{{ scenarios_scenario.spec.tools }}"

    - name: Create role variables
      tags:
        - install_recorders
      when:
        - scenario_id is undefined
      block:
        - name: Create recorders installation variable
          ansible.builtin.set_fact:
            recorders_configuration:
              phase: "{{ benchmark_phase | ansible.builtin.default('pre-fault-injection') }}"
              tools:
                sre:
                  enabled: "{{ tools.sre | ansible.builtin.default(false) }}"
                finops:
                  enabled: "{{ tools.finops | ansible.builtin.default(false) }}"

    - name: Create role variables
      tags:
        - uninstall_recorders
      block:
        - name: Create recorders uninstallation variable
          ansible.builtin.set_fact:
            recorders_storage: "{{ storage }}"

    - name: Import recorders role
      ansible.builtin.import_role:
        name: recorders
      vars:
        recorders_cluster:
          kubeconfig: "{{ cluster.kubeconfig }}"
          platform: "{{ cluster_platform }}"
