name: Run ITBench Unit Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - clusters/kind/go.*
      - scenarios/sre/roles/agent/**
      - scenarios/sre/roles/faults/**
      - scenarios/sre/roles/recorders/**
      - scenarios/sre/roles/tools/**
      - scenarios/sre/roles/waiters/**

concurrency:
  group: ci-unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  environment-recorders:
    name: ITBench Environment Recorders Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7.6.0
      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: clusters/kind/go.mod
          cache-dependency-path: clusters/kind/go.sum
      - name: Install project dependencies
        run: |
          make deps
      - name: Create group vars
        run: |
          make -C scenarios/sre group-vars
      - name: Create Kind cluster
        run: |
          make -C clusters/kind create-simple-cluster
      - name: Run Cloud Provider
        run: |
          make -C clusters/kind run-service-provider &
      - name: Run unit tests
        run: |
          make -C scenarios/sre test-unit-recorders
      - name: Destroy Kind cluster
        run: |
          make -C clusters/kind destroy-simple-cluster
  environment-tools:
    name: ITBench Environment Tools Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7.6.0
      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: clusters/kind/go.mod
          cache-dependency-path: clusters/kind/go.sum
      - uses: azure/setup-helm@v4.3.1
        with:
          version: v3.19.0
      - name: Install project dependencies
        run: |
          make deps
      - name: Create group vars
        run: |
          make -C scenarios/sre group-vars
      - name: Create Kind cluster
        run: |
          make -C clusters/kind create-simple-cluster
      - name: Run Cloud Provider
        run: |
          make -C clusters/kind run-service-provider &
      - name: Run unit tests
        run: |
          make -C scenarios/sre test-unit-tools
      - name: Destroy Kind cluster
        run: |
          make -C clusters/kind destroy-simple-cluster
  sre-agent:
    name: SRE Agent Access Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7.6.0
      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: clusters/kind/go.mod
          cache-dependency-path: clusters/kind/go.sum
      - name: Install project dependencies
        run: |
          make deps
      - name: Create group vars
        run: |
          make -C scenarios/sre group-vars
      - name: Create Kind cluster
        run: |
          make -C clusters/kind create-simple-cluster
      - name: Run unit tests
        run: |
          make -C scenarios/sre test-unit-agent
      - name: Destroy Kind cluster
        run: |
          make -C clusters/kind destroy-simple-cluster
  sre-faults:
    name: SRE Fault Injection Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7.6.0
      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: clusters/kind/go.mod
          cache-dependency-path: clusters/kind/go.sum
      - name: Install project dependencies
        run: |
          make deps
      - name: Create group vars
        run: |
          make -C scenarios/sre group-vars
      - name: Create Kind cluster
        run: |
          make -C clusters/kind create-simple-cluster
      - name: Run unit tests
        run: |
          make -C scenarios/sre test-unit-faults
      - name: Destroy Kind cluster
        run: |
          make -C clusters/kind destroy-simple-cluster
  sre-waiters:
    name: SRE Waiters Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7.6.0
      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: clusters/kind/go.mod
          cache-dependency-path: clusters/kind/go.sum
      - name: Install project dependencies
        run: |
          make deps
      - name: Create group vars
        run: |
          make -C scenarios/sre group-vars
      - name: Create Kind cluster
        run: |
          make -C clusters/kind create-simple-cluster
      - name: Run unit tests
        run: |
          make -C scenarios/sre test-unit-waiters
      - name: Destroy Kind cluster
        run: |
          make -C clusters/kind destroy-simple-cluster
